services:
  # Kafka с поддержкой KRaft (без ZooKeeper) - ОБЯЗАТЕЛЬНО для транзакций
  kafka:
    image: apache/kafka:4.2.0-rc3
    container_name: kafka-local
    hostname: kafka
    ports:
      - "19092:19092"  # Порт для приложения
      - "9093:9093"    # Controller порт для KRaft
    environment:
      # KRaft режим
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "controller,broker"
      KAFKA_LISTENERS: "PLAINTEXT://:19092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:19092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"

#      # НАСТРОЙКИ ДЛЯ ТРАНЗАКЦИЙ (критически важно!)
#      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
#      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
#      KAFKA_TRANSACTION_ABORT_TIMED_OUT_TRANSACTION_CLEANUP_INTERVAL_MS: 10000
#      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: 300000

      # Настройки для долгого хранения (по вашему требованию)
      KAFKA_LOG_RETENTION_HOURS: 24           # 1 день
      KAFKA_LOG_RETENTION_BYTES: -1            # Без ограничения по размеру
      KAFKA_LOG_SEGMENT_BYTES: 1073741824      # 1GB на сегмент
      KAFKA_OFFSETS_RETENTION_MINUTES: 10080   # 7 дней для offsets

      # Настройки для тестов производительности
      KAFKA_NUM_PARTITIONS: 3                  # По умолчанию для новых топиков
      KAFKA_MESSAGE_MAX_BYTES: 10485760        # 10MB макс размер сообщения
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760  # 10MB для репликации

      # Автоматическое создание топиков (для разработки)
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:19092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - kafka-data:/tmp/kraft-combined-logs

  # Kafka UI
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8081:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
      KAFKA_CLUSTERS_0_NAME: "local-kafka"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "localhost:19092"
      KAFKA_CLUSTERS_0_METRICS_PORT: 9999
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  kafka-data: